version: '3.5'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    logging:
      driver: none
  redis:
    image: redis
    ports:
      - 6379:6379
