version: '3.5'
services:
  postgres:
    build:
      context: ../..
      dockerfile: ./development/docker/dev.db.Dockerfile
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    logging:
      driver: none
  redis:
    image: redis
    command: >
      --requirepass password
    ports:
      - 6379:6379
